/* Database schema to keep the structure of entire database. */

CREATE TABLE genres (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  items TEXT [],
  PRIMARY KEY (id)
);

CREATE TABLE items (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  genre_id INT REFERENCES genres (id) ON DELETE CASCADE,
  publish_date DATE,
  archived BOOLEAN,
  PRIMARY KEY (id)
);

CREATE TABLE music_albums (
  album_name VARCHAR(100),
  on_spotify BOOLEAN,
  item_id INTEGER REFERENCES items(id)
) INHERITS (items);
